### ISSUE TITLE
[Refactoring, DA, Documentation] `AnalogRX`'s blockade radius

### ISSUE THREAD

**Issue by CdeTerra** [pasqal-io/qadence#108]
In the [documentation](https://pasqal-io.github.io/qadence/v1.0.1/) on the "digital-analog example" section, one can find the following code:

```python
from torch import pi
from qadence import Register, AnalogRX, sample

# Global analog RX block.
block = AnalogRX(pi)

# Almost non-interacting qubits as too far apart.
register = Register.from_coordinates([(0,0), (0,15)])  # Dimensionless.
samples = sample(register, block)

# Interacting qubits as close together.
register = Register.from_coordinates([(0,0), (0,5)])
samples = sample(register, AnalogRX(pi))
```

We can't see any explanation why 5 should make atoms close and 15 too far apart to interact. These values are arbitrary and in the implementation of `_analog_rot`, the default blockade radius corresponds to omega defaulted to π. This raises the following points:

- Why is omega defaulted to π?
- Regardless of what it's defaulted to, shouldn't the user have access to the corresponding blockade radius to know what is close and what is too far? They could for example do something like:
  ```python
  Register.from_coordinates([(0,0), (0, qadence.default_blockade / 2)]) # close
  Register.from_coordiantes([(0,0), (0, qadence.default_blockade * 2)]) # far
  ```
  This would allow them to make sure they get a specific behavior. It's true they could use `AnalogRot` instead, but they would loose the syntactic sugar of doing X/Y/Z rotations. Besides, functions like `AnalogRX` which behavior is unpredictable may be pointless.

**Comment by Roland-djee** [comment]
Hey @nmheim would you be able to take that one on whenever possible ?
