### ISSUE TITLE
Revisit definition and implementation of qubit interaction

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#116]
### Motivations

Currently, the definition of qubit interaction for supporting backends (PyQTorch and Pulser) is not very modular and does not properly account for different underlying implementations (using `HamEvo` with PyQTorch and native with Pulser). 

It is thus desirable to separate the definition of the interaction in a higher-level interface which would include all information needed to define the interaction independently on the way it is implemented in the backend.

### Proposal

Define a general `Interaction` class which will take into account the following properties:

- interaction type
- custom interaction function
- interaction strength (e.g. blockade radius)
- (optional) Rydberg level
- (optional) local addressing pattern to be added on top of the interaction itself
- etc. etc.

We can have a modular way of creating a Hamiltonian. We might need a `Hamiltonian` object for this purpose.

This would look something like the following:

```python
@dataclass
class Interaction:

	type: InteractionType = InteractionType.NN
	custom_interaction_fn: Callable | None = None
	interaction_coeff: float = None
	rydberg_level: int = 70
	semi_local_addr_patterns: list[AddressingPatterns] = None
	blockade_radius: float = None
	
	# generator for the interaction given the above parameters
  # it spits out a block where all the sub-blocks have been
  # replaced with HamEvo operations with the right generator
	
	# this can replace the current `add_interaction` method
	def add_to_block(self, block: AbstractBlock | Register | QuantumCircuit) -> AbstractBlock:
	  pass	
```

The interaction can then be added either as a `Backend` argument or as an argument in the `QuantumCircuit` constructor. The first is likely preferable since the interaction is associated with the execution backend independently from the given circuit.

```python
class Backend:
	... other attributes
	interaction: Interaction | None = None

       # validate that the given interaction is executable with the
       # chosen backend and fail otherwise. Not every backend can
       # correctly simulate all interactions
       def validate_interaction(self):
           raise NotImplementedError
```

**Comment by nmheim** [comment]
we should also take care of register information here somehow. `AnalogBlock` eigenvalues in the pulser backend are a bit of a mess currently, because they don't have access to qubit positions.

**Comment by vytautas-a** [comment]
I guess we could have an additional argument `register` in `Interaction` class.

**Comment by vytautas-a** [comment]
Speaking of eigenvalues of `ConstantAnalogRotation` maybe they could be calculated after the block Hamiltonian is constructed and then assigned to the respective property. This way the original `ConstantAnalogRotation` blocks will get their corresponding eigenvalues for further use (say, in Pulser backend) and for `pyq` the additional step of converting to `HamEvo` would be applied.

**Comment by madagra** [comment]
Yes, makes sense. Another thing to take into account is the `Device` specifications, I think. The interaction could also be influenced by certain properties of the device, e.g. minimum atomic distance or maximum available amplitude and detuning. These should be taken into account in the constructor. I guess this is related with #119.

**Comment by madagra** [comment]
A useful document for units: http://ilan.schnell-web.net/physics/rydberg.pdf.
