### ISSUE TITLE
[Realistic-sims, Feature, Error] Simulate bit flips and phase flips for digital gates

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#122]
Very likely to be added to the primitive blocks. It should be introduced for both single and two-qubit gates.

**Comment by Roland-djee** [comment]
Ethan's internship.

**Comment by Roland-djee** [comment]
Closing as moved in PyQ. See [here](https://github.com/orgs/pasqal-io/projects/7/views/1?pane=issue&itemId=56356385)
