### ISSUE TITLE
[Feature, Proto, DA, Realistic-sims, Error] Bit flips and phase flips for analog blocks

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#124]
To be investigate on how to best achieve this.

**Comment by Roland-djee** [comment]
@jpmoutinho Would you be willing discussing this at some point ?

**Comment by Roland-djee** [comment]
@EthanObadia We should start thinking about it once we're OK on the digital noise and @vytautas-a implemented the time-dependent generator.

**Comment by mlahariya** [comment]
Moved to PyQ. Not relevant anymore.
