### ISSUE TITLE
[Feature, Proto, Backends, Realistic-sims, Error] Simulate dephasing noise in PyQTorch

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#125]
This should be experimented with since it is not clear how to apply it with analog blocks.

Some useful references (mostly for superconducting qubits): https://scqubits.readthedocs.io/en/latest/bibliography.html#ithier2005.

**Comment by Roland-djee** [comment]
Part of Ethan internship.

**Comment by Roland-djee** [comment]
@EthanObadia Tagging you here as there is a list of references that you might want to have a look at in the description. Might also be useful for your report.

Closing as part of @EthanObadia internship and moved to PyQ. See [here](https://github.com/orgs/pasqal-io/projects/7/views/1?pane=issue&itemId=56356385)
