### ISSUE TITLE
unused `device` arg on `ml_tools.optimize_step` may raise cpu/gpu error

### ISSUE THREAD

**Issue by Doomsk** [pasqal-io/qadence#133]
Currently, on `ml_tools.optimize_step` the [optmize_step](https://github.com/pasqal-io/qadence/blob/7a94d0e11e052a21aa8f1e77e81f222a1cfc639c/qadence/ml_tools/optimize_step.py#L45) function has a `device` argument which is not being used. It may be related with some issues while trying to run `train_grad`-dependent code with `device='cuda'` that raises the following error:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by dominikandreasseitz** [comment]
solved
