### ISSUE TITLE
[Feature, Realistic-sim, Error] Add ZNE error mitigation for digital blocks

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#144]
Should work with PyQ and Braket. Can be tested using the low-level Braket backend which includes noise.

Reference: https://github.com/amazon-braket/amazon-braket-examples/blob/main/examples/braket_features/Simulating_Noise_On_Amazon_Braket.ipynb

**Comment by Roland-djee** [comment]
Ethan internship.

**Comment by Roland-djee** [comment]
Closing as implemented [here](https://github.com/pasqal-io/qadence-protocols/blob/main/qadence_protocols/mitigations/analog_zne.py)
