### ISSUE TITLE
Better document usage of shot-based protocols

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#146]
Currently, there is almost no documentation on how to use tomography and classical shadows protocols.

**Comment by Roland-djee** [comment]
Features to document into a "Realistic Simulations" section of the docs:

- [ ] Measurements
- [ ] Error models
- [ ] Error mitigation

**Comment by madagra** [comment]
Yes, indeed. Thanks, @Roland-djee. This should be a priority and should be addressed directly with #128 or separately.
