### ISSUE TITLE
Visualization for `QuantumModel` instances

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#175]
Allow for calling something like:

```
from qadence.draw import display
from qadence import QuantumModel

qm = QuantumModel(...)
display(qm)
```

**Comment by arthurfaria** [comment]
`display(model._circuit.original)` does the same as `display(qc_ansatz)`. It displays a huge image of the circuit and also does not show the measurements (screenshot attached).

<img width="1373" alt="Screenshot 2023-11-10 at 09 40 42" src="https://github.com/pasqal-io/qadence/assets/12073321/95b1c6f2-2355-4603-8c94-6e39a7865f06">
