### ISSUE TITLE
[Feature, DA, Proto] Transpilation passes with digital-analog transforms

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#179]
Use digital-analog transformations #154 to recast a digital circuit into a digital-analog program.

Details:
* build a sort of digital-analog intermediate representation of the program. This is related to #84. 
* fallback to the digital case if needed
* allow for Pulser compilation, for example
* focus the compilation on the semi-local addressability patterns we have on the machine, see #120.

This is an interesting research-oriented project as well.

**Comment by Roland-djee** [comment]
@kaosmicadei
