### ISSUE TITLE
[Feature, Realistic-sim, Error] Couple digital and analog error mitigation techniques

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#182]
This issue revolves around finding a way to have both digital (e.g. ZNE with unitary unfolding) and analog (e.g. ZNE with pulse stretching) techniques for mitigation working in conjunction with the same digital-analog program.

This is blocked by #144 and #181.

**Comment by Roland-djee** [comment]
Ethan internship.

**Comment by Roland-djee** [comment]
@gvelikova @rajaiitp to discuss on how to move this further
