### ISSUE TITLE
Circuit drawing issue

### ISSUE THREAD

**Issue by hsinyuryanwu** [pasqal-io/qadence#190]
Hi,

There is an issue associated with drawing the circuit.

display(chain(CPHASE(0, 1, pi), CPHASE(0, 2, pi/2), CPHASE(0, 3, pi/4)))

display(chain(CPHASE(0, 1, pi), CPHASE(0, 2, pi/2)))

Please also check the drawing after taking the dagger operation for different qubits.

Hsin-Yu

**Comment by Roland-djee** [comment]
@hsinyuryanwu Thanks for this really. This also relates to another of our issues #42. @nmheim would you be able to pick that up at some point ?
