### ISSUE TITLE
[Feature, Realistic-sim] Extend register layout to 3 dimensions

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#200]
Currently, only 2 dimensions are supported.

**Comment by nmheim** [comment]
Does it make sense to construct registers with flexible 1D/2D/3D coordinates? E.g. 1D could be represented by a map from qubit index to `len(p)==1` tuple:
```python
{
  0: (-1,)
  1: (0,)
  2: (1,)
}
```
and a 2D register with a tuple of length 2:
```python
{
  0: (-1,1)
  1: (0,0)
  2: (1,1)
}```

**Comment by madagra** [comment]
> Does it make sense to construct registers with flexible 1D/2D/3D coordinates? E.g. 1D could be represented by a map from qubit index to `len(p)==1` tuple:
> 
> ```python
> {
>   0: (-1,)
>   1: (0,)
>   2: (1,)
> }
> ```
> 
> and a 2D register with a tuple of length 2:
> 
> ```python
> {
>   0: (-1,1)
>   1: (0,0)
>   2: (1,1)
> }
> ```
> 
> etc.

@nmheim Yes, the idea of this issue is exactly what you are writing here.

**Comment by mlahariya** [comment]
Good to have but low priority. Access if useful.
@pimvenderbosch - can you please check if hardware/protocol teams need this. If this is supported in the hardware.

**Comment by pimvenderbosch** [comment]
I checked with Protocols. 3D layouts are not on the hardware roadmap, and therefor such features won't be required in future. I'll close this issue.
