### ISSUE TITLE
[Testing] More tests / refactor `fill_identities`

### ISSUE THREAD

**Issue by nmheim** [pasqal-io/qadence#211]
The `fill_identities` function is a transpilation pass that adds an identity block to every "empty" slot in a circuit. Currently it is only used for the drawing system. 

It may need a refactor. Currently its a bit complicated/ugly. The following examples can be turned into tests:

```python
b = chain(CNOT(0,1), CNOT(1,2))
b = chain(kron(CNOT(0,1)), kron(CNOT(1,2)))
b = kron(CNOT(0,1))
b = chain(SWAP(0,1), SWAP(0,3))
```

**Comment by mlahariya** [comment]
@jpmoutinho  Check if relevant and could be added to #613.
