### ISSUE TITLE
Dagger/adjoint operation of qd.MCRX/qd.MCRY/qd.MCRZ functions 

### ISSUE THREAD

**Issue by hsinyuryanwu** [pasqal-io/qadence#215]
Hi Qadence team,

display(qd.MCRX([1,2,3],0,pi/2))

display(qd.MCRX([1,2,3],0,pi/2).dagger())
TypeError: MCRX.__init__() takes 4 positional arguments but 6 were given

Please also check
display(qd.MCRY([1,2,3],0,pi/2).dagger())
display(qd.MCRZ([1,2,3],0,pi/2).dagger())

**Comment by vincentelfving** [comment]
thanks @hsinyuryanwu I will look into this today
