### ISSUE TITLE
[Bug] ScaleBlock dagger operation

### ISSUE THREAD

**Issue by vincentelfving** [pasqal-io/qadence#217]
Currently the dagger method of ScaleBlock seems incorrect. Consider the following example:
if we take `3*X(0)` and dagger it, we would expect `3*X(0)`, because X is its own conjugate transpose and 3 is a real number, however, instead we get.
```
[mul: -3.00000000000000] 
└── X(0)
```
which gets a minus sign from somewhere....

If we take `3*Y(0)` and dagger it, we expect `-3*Y(0)`, because `Y.dagger=-Y`, and we do get 
```
[mul: -3.00000000000000] 
└── Y(0)
```
but this is coincidental, because the code gives this result for the wrong reasons (if the X case is fixed simply by removing the minus sign in the `ScaleBlock` implementation of dagger, the Y case will be wrong). 

Furthermore, if the parameter is complex-valued like (3+2i)*X(0) we would imagine the daggered version to be (3-2i)*X(0) but instead we get:
```
[mul: 3.0 + 2.0*I] 
└── X(0)
```
without the conjugatin on the complex number.

Suggested solution, pseudocode for the ScaleBlock method of dagger:
```
def dagger()
     return self.__class__(self.block.dagger(), conjugate(self.parameters))
```

expected difficulties: (sympy) conjugation of general complex expressions.

**Comment by dominikandreasseitz** [comment]
@vincentelfving `because Y.dagger=-Y, and we do get..`, could you clarify this? afaik its not..
