### ISSUE TITLE
[Setup] Running qadence on windows

### ISSUE THREAD

**Issue by AbdullahKazi500** [pasqal-io/qadence#221]
AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
```from torch import pi
from qadence import X, Y, HamEvo, Register, product_state, sample, add

# Define the qubit-qubit interaction term.
def interaction(i, j):
    return 0.5 * (X(i) @ X(j) + Y(i) @ Y(j))  # Compose gates in parallel and sum their contribution.

# Initial state with left-most qubit in the 1 state.
init_state = product_state("100")

# Define a register of 3 qubits laid out in a line.
register = Register.line(n_qubits=3)

# Define an interaction Hamiltonian by summing interactions on indexed qubits.
# hamiltonian = interaction(0, 1) + interaction(1, 2)
hamiltonian = add(interaction(*edge) for edge in register.edges)

# Define and time-evolve the Hamiltonian until t=pi/sqrt(2).
t = pi/(2**0.5)  # Dimensionless.
evolution = HamEvo(hamiltonian, t)

# Sample with 100 shots.
samples = sample(register, evolution, state=init_state, n_shots=100)
```

**Comment by nmheim** [comment]
Hey @AbdullahKazi500, this is just a guess, but this example is running fine with latest versions of torch/numpy installed. Maybe try and update and if things still don't work, post your `pip list` output here.

**Comment by dominikandreasseitz** [comment]
hi @AbdullahKazi500, a quick search (https://github.com/numpy/numpy/issues/23570)  confirms what @nmheim said: its very likely related to your python environment. to help you, we need more information about your setup. OS, python version, numpy/torch versions. thanks!

**Comment by dominikandreasseitz** [comment]
@AbdullahKazi500, can you try:
1. create a _clean_ venv / conda env (nothing preinstalled)
2. using python version 3.9-3.11 (no 3.8 or 3.12)
3. `pip install qadence`
4. run the script below
```
from qadence import X, Y, HamEvo, Register, product_state, sample, add
from torch import pi
# Define the qubit-qubit interaction term.
def interaction(i, j):
    return 0.5 * (X(i) @ X(j) + Y(i) @ Y(j))  # Compose gates in parallel and sum their contribution.

# Initial state with left-most qubit in the 1 state.
init_state = product_state("100")

# Define a register of 3 qubits laid out in a line.
register = Register.line(n_qubits=3)

# Define an interaction Hamiltonian by summing interactions on indexed qubits.
# hamiltonian = interaction(0, 1) + interaction(1, 2)
hamiltonian = add(interaction(*edge) for edge in register.edges)

# Define and time-evolve the Hamiltonian until t=pi/sqrt(2).
t = pi/(2**0.5)  # Dimensionless.
evolution = HamEvo(hamiltonian, t)

# Sample with 100 shots.
samples = sample(register, evolution, state=init_state, n_shots=100)
print(samples)
```

**Comment by dominikandreasseitz** [comment]
> @nmheim and @dominikandreasseitz I have tried the above steps but still it is giving me `AttributeError: module 'pexpect' has no attribute 'TIMEOUT'` error

seems like youre running this in a jupyter notebook?

1. if yes, try running it in your terminal, i.e., not in a notebook
2. if the error persists, please run `pip freeze` and post the output here

**Comment by dominikandreasseitz** [comment]
> > > @nmheim and @dominikandreasseitz I have tried the above steps but still it is giving me `AttributeError: module 'pexpect' has no attribute 'TIMEOUT'` error
> > 
> > 
> > seems like youre running this in a jupyter notebook?
> > 
> > 1. if yes, try running it in your terminal, i.e., not in a notebook
> > 2. if the error persists, please run `pip freeze` and post the output here
> 
> No I am running it in a terminal

can you describe the way you installed `qadence` on your system? and please post the output of `pip freeze`

**Comment by Roland-djee** [comment]
> ```
>   File "c:\users\abdul\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\abdul\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\abdul\Anaconda3\Scripts\pip.exe\__main__.py", line 5, in <module>
>   File "c:\users\abdul\anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 66
>     sys.stderr.write(f"ERROR: {exc}")
>                                    ^
> SyntaxError: invalid syntax```
> ```

From this error message @AbdullahKazi500, it feels very much like there is an issue with your `pip`.

**Comment by Roland-djee** [comment]
> > > ```
> > >   File "c:\users\abdul\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
> > >     "__main__", mod_spec)
> > >   File "c:\users\abdul\anaconda3\lib\runpy.py", line 85, in _run_code
> > >     exec(code, run_globals)
> > >   File "C:\Users\abdul\Anaconda3\Scripts\pip.exe\__main__.py", line 5, in <module>
> > >   File "c:\users\abdul\anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 66
> > >     sys.stderr.write(f"ERROR: {exc}")
> > >                                    ^
> > > SyntaxError: invalid syntax```
> > > ```
> > 
> > 
> > From this error message @AbdullahKazi500, it feels very much like there is an issue with your `pip`.
> 
> so what should I do

It feels like `pip` is getting confused within your conda env. Have you tried installing Qadence outside your env ?

**Comment by dominikandreasseitz** [comment]
@AbdullahKazi500 , it seems like youre using Windows. can you try installing `WSL` (https://learn.microsoft.com/en-us/windows/wsl/install) and do the steps i described in one of my above messages?

**Comment by Doomsk** [comment]
@AbdullahKazi500 can you provide at least the traceback error message? Which environment are you using? Python version? Type `pip list`,
copy it and paste it here, please.

**Comment by Roland-djee** [comment]
Hey @AbdullahKazi500, is there any progress on your issue ?
