### ISSUE TITLE
[Feature] Remove same duration constraint from kronned analog blocks

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#226]
Currently, kronned analog blocks are assumed to be implemented in sequence, meaning that there is no need to keep the constraint of them having the same duration.

**Comment by nmheim** [comment]
If we assume that `kron`ed blocks are executed in sequence, should we consider just forbidding `kron` for analog blocks all together? with qubit support we already have a way to put things on different qubits, so `kron` seems a bit pointless then doesn't it?

**Comment by jpmoutinho** [comment]
Yeah, maybe, I'm not sure. I played a bit with some changes in the current qadence device MR but that one is already huge. We will have to think a bit more about it. But indeed the current pulser implementation does the pulses in sequence, that's why I made it also do it in PyQ. It essentially goes through `AnalogKron` and re-builds it back as a chain of `HamEvo`.
