### ISSUE TITLE
[Visualisation] Qubit ordering issues on some of circuit drawings

### ISSUE THREAD

**Issue by hsinyuryanwu** [pasqal-io/qadence#228]
There are still qubit ordering issues on some of circuit drawings.
For example, circuitC = qd.chain(circuitA, circuitB) and circuitC.dagger().

<img width="831" alt="circuitC dagger" src="https://github.com/pasqal-io/qadence/assets/119811404/3cd3d5a4-e5fa-4d70-8ed1-b6653d9b56b4">

**Comment by nmheim** [comment]
Hey! Yes, we are aware of this bug and it’s a bit of a tricky one because we have to tricky graphviz, which is our underlying drawing library into not reordering wires. @mariuccio might have some input here. He was looking into this a while ago.

**Comment by Roland-djee** [comment]
@nmheim Is this addressed ?
