### ISSUE TITLE
[Refactor] Better use of projectors

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/qadence#268]
Projectors are basic operations in quantum mechanics defined in Qadence by being the outer product between ket and bra bitstrings. It is represented by the `ProjectorBlock` [here](https://github.com/pasqal-io/qadence/blob/4fd13d7dfda8aa6c794f75bdb0b9122d8750ac5a/qadence/blocks/primitive.py#L489).

More complex operations and algorithms can be built on top of projectors. However, there are few places in Qadence where projectors can be used as a replacement for built-in operations. In particular:

- [ ] Measurements protocols:
  - [ ] Shadows ([here](https://github.com/pasqal-io/qadence/blob/c64ed022e908514beac5d718a67f213464afff8b/qadence/measurements/shadow.py#L39))
- [ ] Overlap ([here](https://github.com/pasqal-io/qadence/blob/c64ed022e908514beac5d718a67f213464afff8b/qadence/overlap.py#L26) and [here](https://github.com/pasqal-io/qadence/blob/c64ed022e908514beac5d718a67f213464afff8b/qadence/overlap.py#L41))

**Comment by Roland-djee** [comment]
@dominikandreasseitz @jpmoutinho Does it sound OK to you guys ?

**Comment by jpmoutinho** [comment]
Yes 👍

Should it really be changed in the Shadows though? There you use the matrix directly, not the block.

**Comment by Roland-djee** [comment]
> Yes 👍
> 
> Should it really be changed in the Shadows though? There you use the matrix directly, not the block.

Yes, but you can `block_to_tensor` it.

**Comment by king-p3nguin** [comment]
Hi, I would like to work on this issue for unitaryhack.

**Comment by Roland-djee** [comment]
> Hi, I would like to work on this issue for unitaryhack.

Hi @king-p3nguin thanks for your interest in working on Qadence ! Feel free to ask questions here if you find anything unclear and raise a PR for your solution.
