### ISSUE TITLE
[Visualisation] Multi-row partitioning of long-circuit illustrations

### ISSUE THREAD

**Issue by lorenzocardarelli** [pasqal-io/qadence#302]
qadence.draw seems to illustrate circuits in one single row - see [this](https://pasqal-io.github.io/qadence/latest/qml/qaoa/) QAOA tutorial.

```
circuit = QuantumCircuit(n_qubits, final_b)
from qadence.draw import html_string # markdown-exec: hide
print(html_string(circuit)) # markdown-exec: hide
```

When the circuit is deep, the height is shrunk to fit the image in the available frame. Partitioning the circuit in multiple rows with limited depth would improve the visibility.

**Comment by mlahariya** [comment]
@jpmoutinho please add this to #613
