### ISSUE TITLE
[Testing] Speed up Test Suite, Push Code Coverage above 90%

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#311]
Main bottlenecks:
1. not using pytest-xdist (TOP prio which has been investigated by both @seitzdom and @m.dagrada only to result in issues with gitlab runners, this however change when we switch to github) 
2. shadows/tomography
3. PSR tests in general
4. PSR tests which compute higher order derivatives
5. tests which train models (ML tools)
6. redundant test cases in many mark.parametrize-tests
7. tests which do exactly the same thing, like in test_quantum_models and test_backends for example (test run,sample, expectation for random circuits)

**Comment by jpmoutinho** [comment]
@dominikandreasseitz maybe some of the above has already been done, could you check and update? Thanks

**Comment by Roland-djee** [comment]
@dominikandreasseitz @jpmoutinho Is it still relevant ? Some of these tests have move in few other places.
