### ISSUE TITLE
[Feature] Add symbolic Pauli algebra

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#312]
Basically, consider 2-qubit register, then `X^X` * `X^X` = `II`.

In `openfermion` we can also call `reduce()` method to simplify the sum of such Pauli operators (e.g. Pauli strings that cancel out).

Related to having symbolic block system, and can be part of a larger suite of operations on symbolic blocks.

**Comment by Roland-djee** [comment]
@jpmoutinho @Doomsk @kaosmicadei Is this something we take into account in the new block system ?

**Comment by Doomsk** [comment]
> @jpmoutinho @Doomsk @kaosmicadei Is this something we take into account in the new block system ?

The idea is basically to handle identity operator alone as an "empty" expression, since it does not affect the state being manipulated, should be basically ignored

**Comment by kaosmicadei** [comment]
Yes, the expression system converts `X(i) X(i) -> 1` (more specifically, to the neutral element of the multiplication).

**Comment by Roland-djee** [comment]
Cool, is it safe if I close it then ? @jpmoutinho ?

**Comment by jpmoutinho** [comment]
Yes sure, this was a port of a gitlab issue but not much information to go on about.
