### ISSUE TITLE
[Refactor] Redefine block support properties

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#334]
Lengthy discussion in respective gitlab issue.

**Comment by Roland-djee** [comment]
@jpmoutinho Is what you meant here is captured in other issues ?

**Comment by Roland-djee** [comment]
> @Roland-djee there are many comments related to this in the gitlab issue with the same name (that you originally started), I just haven't gone through them to extract the relevant information to move everything here.

OK got it. Do you intend to do it ? Otherwise we can just close and re-open later if not immediately relevant.

**Comment by Roland-djee** [comment]
Closing as moved elsewhere.
