### ISSUE TITLE
[Enhance] Add support for Python 3.12

### ISSUE THREAD

**Issue by awennersteen** [pasqal-io/qadence#335]
According to https://github.com/pytorch/pytorch/issues/110436 PyTorch 2.2 has at least some Python 3.12 support now.

**Comment by Roland-djee** [comment]
We should ditch 3.9 then.

**Comment by awennersteen** [comment]
Why? 3.9 still has 1 year, 8 months left until EOL.

Agree that if something pops up where we have to change code to build around support both we can ditch 3.9, but why would we ditch it just because?

**Comment by Roland-djee** [comment]
> Why? 3.9 still has 1 year, 8 months left until EOL.
> 
> Agree that if something pops up where we have to change code to build around support both we can ditch 3.9, but why would we ditch it just because?

Not just because. My experience is that it is kinda painful to support more than 3 Python versions back. But it is biased because the package contained compiled code. Here, for pure Python, it might be less of a hassle.

**Comment by Roland-djee** [comment]
@awennersteen Torch doesn't play nicely with py3.12, right ? This is why you closed the issue on PyQ ?

**Comment by awennersteen** [comment]
Actually it got sorted with Torch, and in PyQ it's been enabled for 3.12. With the next release of PyQ we can bump it here too

**Comment by dominikandreasseitz** [comment]
closing since its supported now
