### ISSUE TITLE
[Refact] Make time-dependent HamEvo use PyQ

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#339]
Edit: previous issue text:

> Currently the calculation of HamEvo is being done directly in the `convert_ops.py` file of each backend, ignoring the same code that exists in PyQTorch / Horqrux. This was done as a temporary step before a larger effort to clean up the HamEvo calculation.
> 
> Related to #134.

**The above is mostly solved already: https://github.com/pasqal-io/qadence/pull/531**

However the logic for the time-dependent HamEvo is still done in the `convert_ops.py`. Once  https://github.com/pasqal-io/pyqtorch/pull/228 is done, we can look into moving also the time-dependent logic.

**Comment by jpmoutinho** [comment]
Assigning this to you @dominikandreasseitz since that's what you just started doing 😄

**Comment by vytautas-a** [comment]
Completed with PR #568
