### ISSUE TITLE
Testing pauli decomposition for parametric observables

### ISSUE THREAD

**Issue by rajaiitp** [pasqal-io/qadence#347]
Need to add test cases for iterate_pauli_decomposition that is used to break an observable into pauli terms defined in utils.py

**Comment by jpmoutinho** [comment]
Hi @rajaiitp, thanks, could you add a bit more details? Did you find something not working that is not tested?

**Comment by Roland-djee** [comment]
Hey @rajaiitp any further insights on this ?

**Comment by rajaiitp** [comment]
Not sure what this one is relating to, it might be related to the test cases written for iterate_pauli_decomposition on qadence using unroll_block_with_scaling  bug : 

https://github.com/pasqal-io/qadence/issues/358 
that I opened later. Sorry about the lack of description. I will close this one
