### ISSUE TITLE
Add test cases for twirl error mitigation to test multiple backends and strategies

### ISSUE THREAD

**Issue by rajaiitp** [pasqal-io/qadence#348]
Add more test cases for twirl free mitigation,

https://github.com/pasqal-io/qadence/pull/337#discussion_r1494684142

"I would try to iterate over backends to check if there isn't any issue. Also, I would try to use the random circuit/observable generation functionality in strategies.py. I think it would make for a better quality test."

**Comment by Roland-djee** [comment]
@rajaiitp Is this issue in protocols now ?

**Comment by rajaiitp** [comment]
Yup, we have 2 issues that cover it, 
https://github.com/pasqal-io/qadence-protocols/issues/20 
https://github.com/pasqal-io/qadence-protocols/issues/18

I will close this one
