### ISSUE TITLE
[Proto, BS] Provide qubit indices as list for multiqubit gates

### ISSUE THREAD

**Issue by Doomsk** [pasqal-io/qadence#350]
@Roland-djee says:
This would help avoiding potential syntactic errors and making gate implementation more robust by distinguishing from parameter:

```
CRX(0, 1, 0.5) -> CRX([0, 1], 0.5)
```

**Comment by Roland-djee** [comment]
> @Roland-djee says: This would help avoiding potential syntactic errors and making gate implementation more robust by distinguishing from parameter:
> 
> ```
> CRX(0, 1, 0.5) -> CRX([0, 1], 0.5)
> ```

Yes. @dominikandreasseitz also had another approach in PyQTorch, that all gates have a `target` and `control` argument. Correct me if I'm wrong Dominik but this avoids to have a `ControlledGate` type of some sort.

**Comment by Roland-djee** [comment]
Closing as moved elsewhere
