### ISSUE TITLE
Introduce PRECISION env variable 

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/qadence#364]
Currently, the dtype is hardcoded to complex128, lets make it easily changable by introducing a global env variable which can be set by the user

- check for hardcoded dtype setting in: block_to_tensor, block_to_diagonal, backends

**Comment by Roland-djee** [comment]
Can be closed @dominikandreasseitz ?

**Comment by dominikandreasseitz** [comment]
Yes, i thought it is already
