### ISSUE TITLE
[Refactoring] Avoid calling block to tensor on diagonal Hamiltonians

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#368]
When calling `HamEvo` on diagonal Hamiltonians the dense matrix is built but then only the diagonal is taken. 

This is currently done in the `PyQHamiltonianEvolution` class in [`qadence/backends/pyqtorch/convert_ops.py`](https://github.com/pasqal-io/qadence/blob/main/qadence/backends/pyqtorch/convert_ops.py), where the `__init__` method first builds the full matrix `hmat`, and then the `_unitary` method defines the evolution function for diagonal operators which runs `diagonal()` on the full hamiltonian matrix.

We should instead build only the diagonal. For non-parametric block this is directly possible with the function `block_to_diagonal`, as done in the `PyQObservable` class in the same file.

Handling parametric blocks is out of the scope of this issue, and can be done separately. It requires further development in the `block_to_tensor` side as detailed in https://github.com/pasqal-io/qadence/issues/394.

NOTE: Due to ongoing changes in the codebase, we might need to implement this directly in the PyQTorch backend (https://github.com/pasqal-io/pyqtorch/issues/175).

**Comment by Roland-djee** [comment]
@jpmoutinho It feels like it's been handled somewhere unless I'm wrong ?

**Comment by neogyk** [comment]
Dear all,
I am trying to solve this issue.
Is it will be enough to add the following lines to the `PyQHamiltonianEvolution` class constructor:

`        elif not block.generator.is_parametric and block.generator.diagonal:
            m = block.generator.to(dtype=cdouble)
            hmat = block_to_diagonal(
                MatrixBlock(m, qubit_support=block.qubit_support),
                qubit_support=self.qubit_support,
                use_full_support=False,
            )
            hmat = hmat.permute(1, 2, 0)
            self.register_buffer("hmat", hmat)
            self._hamiltonian = lambda self, values: self.hmat`

**Comment by jpmoutinho** [comment]
Hey @neogyk, thanks for your interest in completing this issue!

The solution should be along those lines, but there is no need to use `MatrixBlock`. You should be able to run `block_to_diagonal` on the `block.generator`.

Feel free to open an MR and add me as a reviewer, then we can discuss it there.

**Comment by neogyk** [comment]
Dear @jpmoutinho, could you please review the changes. I made the PR - #441

**Comment by Roland-djee** [comment]
> Dear @jpmoutinho, could you please review the changes. I made the PR - #441

Dear @neogyk, just for your information, @jpmoutinho is off today. He will catch-up as soon as he's back, ie. tomorrow. Thanks.

**Comment by jpmoutinho** [comment]
Closing this issue as completed by @neogyk. The solution will remain unmerged in #478 as explained there.
