### ISSUE TITLE
[Enhance] Add 'backend' argument to product_state

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/qadence#370]
Description:

Refactor [`product_state`]((https://github.com/pasqal-io/qadence/blob/main/qadence/states.py#L187), such that it accepts a `backend: str` argument and returns a product state in the backends _native_ representation. A native representation uses native types for the backend in question.

Implementation:

1. This can _for example_ be achieved by simply using [`product_block`](https://github.com/pasqal-io/qadence/blob/main/qadence/states.py#L376) and calling [`qadence.run`](https://github.com/pasqal-io/qadence/blob/main/qadence/execution.py#L34) on it using the particular requested `backend`. 

2. Add tests which ensure that your implementation works for the backends `pyqtorch` and `horqrux`

**Comment by SaashaJoshi** [comment]
Hey, 
I am trying to solve this issue. I have a few questions. 

1. Am I correct in undersatnding that a `native` representation, particularly for `pyqtorch` and `horqrux`, would be a `tensor` and an `Array` respectively?
2. `qadence.run` requires a circuit. So, the first step would be to construct one from the bitstring argument. Is this correct?

I am opening a PR with what I understood on the first try. Let me know if you were pointing to something different!

**Comment by dominikandreasseitz** [comment]
> Hey, I am trying to solve this issue. I have a few questions.
> 
> 1. Am I correct in undersatnding that a `native` representation, particularly for `pyqtorch` and `horqrux`, would be a `tensor` and an `Array` respectively?
>    ~2. `qadence.run` requires a circuit. So, the first step would be to construct one from the bitstring argument. Is this correct?~
> 
> I am opening a PR with what I understood on the first try. Let me know if you were pointing to something different!

Hi @SaashaJoshi , thanks for participating! I assigned the issue to you.
1. Yes, you are correct. A product state can simply be translated into a circuit, so you can use `qadence.states._block_from_bitstring` to translate a bitstring into a native qadence block. then you need to call `run` using the requested backend. Please tag me on your PR
