### ISSUE TITLE
[Feature, Refactoring] Improve readout noise model 

### ISSUE THREAD

**Issue by gvelikova** [pasqal-io/qadence#383]
* allow for correlated noise following https://arxiv.org/abs/2006.14044

Other links:
https://journals.aps.org/pra/abstract/10.1103/PhysRevA.103.042605
An implementation is available at https://qiskit-community.github.io/qiskit-experiments/stubs/qiskit_experiments.library.characterization.CorrelatedReadoutError.html

**Comment by Roland-djee** [comment]
@gvelikova Would you have time to have a look this sprint ?
