### ISSUE TITLE
[Exploratory] Assess if using 'tensordict' could be adopted in QuantumModel

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/qadence#386]
Pytorch recently added the https://github.com/pytorch/tensordict coincides with the qadence convention of using the `values` paramter dict

**Comment by mlahariya** [comment]
@mlahariya review is relevant.

**Comment by mlahariya** [comment]
To be transferred to PyQ. https://github.com/pasqal-io/pyqtorch/issues/157
