### ISSUE TITLE
[Refact] Reviewing block generators

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/qadence#397]
Related to https://github.com/pasqal-io/qadence/issues/266

All unitary operators have an hermitian generator such that
$$\hat{U}=exp(-i\hat{H})$$
In Qadence we have `block.generator` which is supposed to return $\hat{H}$. However, if we want to use `HamEvo` to then represent the original unitary, we have to specify a time value since it implements $exp(-i\hat{H}t)$. Currently, some blocks seems to have some inconsistent definitions.

This also affects GPSR, since there the paper assumes a generator structure of $exp(-iG/2x)$ for some gate $U(x)$.

Probable requirements:
- Make all gates follow the GPSR format, as suggested in https://github.com/pasqal-io/qadence/issues/266
- Have a specific GPSR function to handle `HamEvo` differentiation, so that any arbitrary `HamEvo(G, x)` is processed in a way that the the $1/2$ factor is "considered" in $G$, and $x$ is an angle.

**Comment by Roland-djee** [comment]
@jpmoutinho You mentioned something about it in the planning, right ?

**Comment by jpmoutinho** [comment]
@Roland-djee yes, for @chMoussa to be aware of this while planning how GPSR is integrated into pyqtorch

**Comment by chMoussa** [comment]
Closing with #526
