### ISSUE TITLE
[Proto] Qadence Tree

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/qadence#399]
A prototype to replace whats now the `Converted` class to store all relationships between abstract,native and parameters with a dag which can be mapped over.  Whats now under 'qadence/tree.py' could for example be added to the QuantumCircuit class. lmkwyt

**Comment by Roland-djee** [comment]
@dominikandreasseitz @Doomsk @kaosmicadei @jpmoutinho Possible feature for Qadence refactoring.

**Comment by jpmoutinho** [comment]
Closing given the issue created in the new expression system.

**Comment by Roland-djee** [comment]
@jpmoutinho @Doomsk @kaosmicadei It feels this is what the IR is supposed to represent. Would it make sense to close it ?

**Comment by jpmoutinho** [comment]
@Roland-djee I think we can

**Comment by Roland-djee** [comment]
OK we can re-open if needed.
