### ISSUE TITLE
[Performance] Expand PyQComposedBlock to 2 qubit gates

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/qadence#40]
Modify https://github.com/pasqal-io/qadence/blob/main/qadence/backends/pyqtorch/convert_ops.py#L198 so that its able to merge multi qubit gates acting on the same qubits into a single [torch.tensordot](https://pytorch.org/docs/stable/generated/torch.tensordot.html) operation

Some remarks:
1. Identify the correct conditions in which multi quibit gates can be merged. Feel free to take inspiration from https://github.com/pasqal-io/horqrux/blob/main/horqrux/apply.py#L73
2. Add tests which check that your solution gives the same result as the un-merged version
3. Nice to have: Add some benchmarks which `timeit` to check how much speedup you achieved for a certain problem

**Comment by jpmoutinho** [comment]
Hi @ducthanh1991, thanks for your interest in this issue. To start it off, it would be easier to consider only merging gates acting on the same qubit support, including the same control qubit.

One option that I am not sure if @dominikandreasseitz had in mind or not is to also merge single-qubit gates together with two-qubit gates if the support of the single-qubit one is included in the two-qubit merger.

**Comment by ducthanh1991** [comment]
Hi @jpmoutinho, @dominikandreasseitz ,

Thanks for the recommendations! I was wondering why it was necessary to defined a parameter `qubits` for `PyQComposedBlock`? From my understanding, it takes a list of `Primitives` to instantiate the class. One could use the method `target` of the `Primitives` to define the list of `qubits`. Or is there something else that I am missing?

**Comment by dominikandreasseitz** [comment]
> Hi @jpmoutinho, @dominikandreasseitz ,
> 
> Thanks for the recommendations! I was wondering why it was necessary to defined a parameter `qubits` for `PyQComposedBlock`? From my understanding, it takes a list of `Primitives` to instantiate the class. One could use the method `target` of the `Primitives` to define the list of `qubits`. Or is there something else that I am missing?

@ducthanh1991 sure thats also possible. its just the way we chose to do it at the time. by the way, are you officially taking over the issue?

**Comment by ducthanh1991** [comment]
Hi @dominikandreasseitz, yes I would like to be assigned to this issue.

**Comment by ducthanh1991** [comment]
@dominikandreasseitz , @jpmoutinho, in wich file can I put the test?

**Comment by ducthanh1991** [comment]
Hello @dominikandreasseitz, @jpmoutinho ,

Could you review my work [PR 447](https://github.com/pasqal-io/qadence/pull/447)?
