### ISSUE TITLE
[Testing] Add tests for new Pulser SimConfig API

### ISSUE THREAD

**Issue by RolandMacDoland** [pasqal-io/qadence#414]
Since Pulser API is changing, there must be some tests to check compliance with `SimConfig` for mitigation purposes.

**Comment by dominikandreasseitz** [comment]
@rajaiitp was that solved by #410 or #427 ?

**Comment by Roland-djee** [comment]
@dominikandreasseitz I don't think it was with either. I should add it.

**Comment by dominikandreasseitz** [comment]
@rajaiitp @Roland-djee @gvelikova i just tried to run the tests on protocols using the newest qadence and a lot of them fail. could it be related to this?

**Comment by Roland-djee** [comment]
> @rajaiitp @Roland-djee @gvelikova i just tried to run the tests on protocols using the newest qadence and a lot of them fail. could it be related to this?

I fixed some of them in a local branch. Will push it soon.

**Comment by Roland-djee** [comment]
@rajaiitp Do you have something specific in mind about this ? Otherwise, I will close it.
