### ISSUE TITLE
[Bug] Review GPSR with degenerate spectrum

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#426]
As mentioned by @vytautas-a:

_I made some calculations and experiments related to this problem (in context of GPSR) and it seems that it is two-fold: one related to numerical stability of linear system solver and another more fundamental and related to the spectral structure of some generators. For example, `G=4*X(0)+2.001*X(1)`  is handled perfectly, however `G=4*X(0)+2*X(1)`  - fails. The first case has 4 distinct spectral gaps, 2 of which are very close to 8, the other - only three. It seems that such degeneracy in eigenspectrum breaks down the method because the numerical solver has to deal with linear equation system that has certain symmetry._

**Comment by jpmoutinho** [comment]
Hey @chMoussa, can you take a look at this issue and check if this is a problem in the current PyQ implementation of GPSR? Thanks!

**Comment by chMoussa** [comment]
Hey @jpmoutinho I tried this by adding these two cases in the `test_hamevo_gpsr` in the `test_gpsr` and tests pass. So I think we are good here.

**Comment by jpmoutinho** [comment]
Ok nice thanks for checking :)
