### ISSUE TITLE
[Bug] get_latest_checkpoint_name() looks for the wrong ckpt name

### ISSUE THREAD

**Issue by inafergra** [pasqal-io/qadence#475]
The function `get_latest_checkpoint_name()` is not able to retrieve the last checkpoint name for both optimizers and models. I believe the issue is in `write_checkpoint()` when the `model_checkpoint_name` and `opt_checkpoint_name` are defined. When the `device` was included in the checkpoint name, it should have been included before `iteration_substring` in the string names, so that it matches the pattern defined by `pattern = re.compile(".*_(\d+).pt$")` in `get_latest_checkpoint_name`.

This is, the model's checkpoint name should be:
```
model_checkpoint_name: str = (
        f"model_{type(model).__name__}_ckpt"
        + f"_device_{device}"
        + f"_{iteration_substring}"
        + ".pt"
    )
```
and same with the optimizer's checkpoint. 

The tests in `test_checkpointing.py` are passing because they do not correctly test for `get_latest_checkpoint_name()`. When a checkpoint is not found in the `load_model()` function, it just returns the `model` passed as an argument, so that when comparing the parameters of the model pre- and post- loading the checkpoint they are equal even if the saved model was really not loaded. Same with optimizers I believe. For example, when running `pytest tests/ml_tools/test_checkpointing.py -s` to print the warnings, the following type of warning shows:
```
WARNING 2024-06-20 12:45:16 - qadence.ml_tools.saveload: Unable to load state dict due to [Errno 21] Is a directory: '/tmp/pytest-of-ina/pytest-21/test_basic_save_load_ckpts0'.               No corresponding pre-trained model found. Returning the un-trained model.
ERROR 2024-06-20 12:45:16 - qadence.ml_tools.saveload: Directory /tmp/pytest-of-ina/pytest-21/test_basic_save_load_ckpts0 does not contain any opt checkpoints.
```

I can make a draft PR with the changes.

**Comment by dominikandreasseitz** [comment]
hey @inafergra i started fixing this in #434 but i didnt finish it so far
