### ISSUE TITLE
[Bug] Model's `state_dict` not loading properly when loading a ckpt

### ISSUE THREAD

**Issue by inafergra** [pasqal-io/qadence#484]
Right now, when loading model checkpoints (`QuantumModel` or `QNN`) the `state_dict` of the model is not loaded properly. The issue is in the `load_model()` function, which treats the `QuantumModel.from_dict()` classmethod as an in-place operation 

https://github.com/pasqal-io/qadence/blob/70e12d47509b4f737cb3dbf93b7fd773e77e6eb9/qadence/ml_tools/saveload.py#L114-L116
 
when in reality `.from_dict()` is a class method and does not act as an in-place operation, as it returns a new class instance with the parameters taken from the input model `state_dict`:

https://github.com/pasqal-io/qadence/blob/70e12d47509b4f737cb3dbf93b7fd773e77e6eb9/qadence/model.py#L276-L308

The most straightforward solution would be to do `model = model.from_dict()` when loading the `state_dict`. However, this doesn't work since then, when using the `train_grad()` loop, the parameters passed to the optimizer before the training loop do not correspond to the newly created instance of the model, and therefore the parameters won't be updated in `optimizer.step()`. 

One solution would be to make `.from_dict()` an instance method instead of a class method so that it acts as an in-place operation, by mutating the instance attributes instead of creating a new instance. This might cause some additional issues (@dominikandreasseitz mentioned the uuid assignments might cause problems?)

**Comment by inafergra** [comment]
Tagging @dominikandreasseitz @jpmoutinho @Roland-djee

**Comment by Roland-djee** [comment]
> Tagging @dominikandreasseitz @jpmoutinho @Roland-djee

Thanks for this @inafergra. I guess @dominikandreasseitz or @chMoussa are the best placed to have a look ?

**Comment by dominikandreasseitz** [comment]
> > Tagging @dominikandreasseitz @jpmoutinho @Roland-djee
> 
> Thanks for this @inafergra. I guess @dominikandreasseitz or @chMoussa are the best placed to have a look ?

thanks @inafergra. @Roland-djee , since @inafergra already knows how to solve it he could coordinate with @chMoussa on fixing this. i can ofc also do it. Let me know

**Comment by Roland-djee** [comment]
> > > Tagging @dominikandreasseitz @jpmoutinho @Roland-djee
> > 
> > 
> > Thanks for this @inafergra. I guess @dominikandreasseitz or @chMoussa are the best placed to have a look ?
> 
> thanks @inafergra. @Roland-djee , since @inafergra already knows how to solve it he could coordinate with @chMoussa on fixing this. i can ofc also do it. Let me know

If that is fine with them sure.

**Comment by Roland-djee** [comment]
@inafergra @chMoussa Would you be able to coordinate on this ?
