### ISSUE TITLE
Using len(qubit_support) instead of qubit_support[0] to get number of qubits.

### ISSUE THREAD

**Issue by caspergyurik** [pasqal-io/qadence#491]
https://github.com/pasqal-io/qadence/blob/bfd4c4c4048f2bb76829667adceb3798d8d78017/qadence/blocks/primitive.py#L514

**Comment by Roland-djee** [comment]
Thanks for this @caspergyurik could you please also post what caused the bug ?

**Comment by caspergyurik** [comment]
n_qubits = 4
all_zero = "0"*n_qubits
projector = ProjectorBlock(all_zero, all_zero, n_qubits)

**Comment by Roland-djee** [comment]
@caspergyurik This error is actually sensible: what you pass as `qubit_support` is the number of qubits. `qubit_support` is the set of qubit indices you want your operation to work on. It works if you do:

```python
n_qubits = 4
all_zero = "0"*n_qubits
projector = ProjectorBlock(all_zero, all_zero, (0, 1, 2, 4)) <-- passing the qubit support
```
