### ISSUE TITLE
[Bug] Using simple `float` values inside `sympy` function leads to incorrect wavefunction when using time-dependent block

### ISSUE THREAD

**Issue by vytautas-a** [pasqal-io/qadence#492]
Say we define a time-dependent generator for `HamEvo`:
```
td_gen = omega * (sympy.sin(x * t) * X(0) + y * (t**2) * Y(1))
```

If `x` and `y` are instances of `Parameter` (`t` is the time parameter) the result of simulating `HamEvo` with such generator is correct. However, if either or both `x` and `y` are floats or tensors - the simulation result is wrong.

**Comment by Roland-djee** [comment]
@vytautas-a Would you be able to give it a try ?

**Comment by jpmoutinho** [comment]
To check again in PyQ once https://github.com/pasqal-io/pyqtorch/pull/228 is done.

**Comment by vytautas-a** [comment]
Fixed by PR https://github.com/pasqal-io/qadence/pull/568
