### ISSUE TITLE
Mismatch in custom rotations key in AnsatzConfig class

### ISSUE THREAD

**Issue by n-toscano** [pasqal-io/qadence#513]
`strategy_args.operations` [definition](https://github.com/pasqal-io/qadence/blob/813d48dcc39c869b07457cddefa292e3f594d2b9/qadence/ml_tools/config.py#L403) does not match `_create_hea_digital` request for ["rotations" ](https://github.com/pasqal-io/qadence/blob/813d48dcc39c869b07457cddefa292e3f594d2b9/qadence/ml_tools/constructors.py#L490).

**Comment by smitchaudhary** [comment]
Thanks for pointing out. Will have a look at it and push the fix.

**Comment by n-toscano** [comment]
Since @giovanniminutoNL found this, I thought it would make a good (and quick) first contribution to the repo – unfortunately I cannot point out _assignees_. Would you make everything consistent with `operations` or `rotations`?

**Comment by smitchaudhary** [comment]
Indeed. I would let him do the needful in that case. It is `operations` everywhere, that was an oversight on my end. I would just do `operations`.

**Comment by smitchaudhary** [comment]
Fixed in #515
