### ISSUE TITLE
[Refactoring] [Testing] Noise 

### ISSUE THREAD

**Issue by chMoussa** [pasqal-io/qadence#583]
Folowing the digital noise MR #563, a few extra tasks are to be carried out:

- Properly making consistent the DigitalNoise with the Noise class and etc... Some are backend independent (Readout), others are analog/digital-specific. It makes sense to separate the different types.
- Including the noise in each block string: if added, check how it behaves with visualization.
- Serialization: make `_to_dict` and `_from_dict` functions to noise class
- Add tests! For transpiler functions such as `set_noise`

**Comment by chMoussa** [comment]
At the same time, tackle #369

**Comment by mlahariya** [comment]
@chMoussa closing this as most things are already implemented. Visualization which is left will be added to mega visualization issue. #613
