### ISSUE TITLE
Replace empty lists, and dicts by default `None` on functions and methods args

### ISSUE THREAD

**Issue by Doomsk** [pasqal-io/qadence#590]
### Short description

Empty lists, tuples, dicts as defaults on functions and methods declarations are prone to changing their default values if the variable in the argument is changed throughout the function/method scope.

### Steps/Code to reproduce

```python

def fn(x=[]):
    x.append(1)
    return x

print(fn())
print(fn([2,3]))
print(fn())
```

### Would you like to work on this issue?

Yes

**Comment by chMoussa** [comment]
Closing with #594
