### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/qadence#68]
Finalising the docs review and suggestions for improvements.

**Comment by gvelikova** [comment]
I don't know where I should put this find, so I will try it here: 

'Solve a QUBO oroblem'

**Comment by Roland-djee** [comment]
> I don't know where I should put this find, so I will try it here:
> 
> 'Solve a QUBO oroblem'

Not sure what you meant @gvelikova

**Comment by Roland-djee** [comment]
> I thought that there is a mistake and it should be QUBO problem? And I saw that the references in 'Variational quantum algorithms' docs section are not displayed in the same way (and properly).

Still don't quite get it.

**Comment by gvelikova** [comment]
here https://pasqal-io.github.io/qadence/v1.0.0/qml/

## References

[^1]: Schuld, Petruccione, Machine learning on Quantum Computers, Springer Nature (2021)

[^2]: [Kyriienko et al., General quantum circuit differentiation rules](https://arxiv.org/abs/2108.01218)

**Comment by gvelikova** [comment]
And  here  https://pasqal-io.github.io/qadence/v1.0.0/digital_analog_qc/analog-qubo/

it is in the title 

`Solve a QUBO oroblem`

**Comment by Roland-djee** [comment]
> And here https://pasqal-io.github.io/qadence/v1.0.0/digital_analog_qc/analog-qubo/
> 
> it is in the title
> 
> `Solve a QUBO oroblem`

Fixed.
